#!/bin/bash

# deploy.sh
# Automates initial deployment of charms-indexer to Fly.io with PostgreSQL.
# Run from: /path/to/charms-explorer/indexer
# For redeployment, use redeploy.sh instead.

# Exit on error, treat unset variables as errors
set -eu

echo "🚀 Starting initial deployment of charms-indexer to Fly.io..."

# Step 1: Verify prerequisites
echo "🔍 Step 1: Checking prerequisites..."
for cmd in flyctl docker; do
    command -v "$cmd" >/dev/null 2>&1 || { echo "❌ Error: $cmd not found. Please install it."; exit 1; }
done
flyctl auth whoami >/dev/null 2>&1 || { echo "❌ Error: Not logged into Fly.io. Run 'flyctl auth login'."; exit 1; }
echo "✅ Prerequisites verified."

# Step 2: Check if fly.toml exists and handle app creation
if [ -f "fly.toml" ]; then
    echo "📋 Found existing fly.toml file."
    app_name=$(grep "app =" fly.toml | cut -d '"' -f2 || grep "app =" fly.toml | cut -d "'" -f2 || echo "charms-explorer-indexer")
    echo "📋 App name from fly.toml: $app_name"
    
    # Check if the app actually exists on fly.io
    if flyctl status --app "$app_name" &>/dev/null; then
        echo "✅ App $app_name exists on Fly.io."
        read -p "Use existing app? (y/n): " use_existing
        if [[ "$use_existing" != "y" ]]; then
            echo "🚀 Creating new app configuration..."
            echo "This will create a new app on Fly.io and generate a new fly.toml file."
            echo "When prompted, select 'No' for deploying now, as we need to set up the database first."
            flyctl launch --no-deploy
            
            # Get the app name from the newly generated fly.toml
            app_name=$(grep "app =" fly.toml | cut -d '"' -f2 || grep "app =" fly.toml | cut -d "'" -f2 || echo "charms-explorer-indexer")
            echo "📋 New app name from fly.toml: $app_name"
        else
            echo "✅ Using existing app: $app_name"
        fi
    else
        echo "⚠️ Warning: App $app_name defined in fly.toml does not exist on Fly.io yet."
        echo "   We need to create it first."
        
        read -p "Create app with name $app_name? (y/n): " create_app
        if [[ "$create_app" == "y" ]]; then
            echo "🚀 Creating new app with name $app_name..."
            flyctl apps create "$app_name" --org charms-inc
            echo "✅ App $app_name created on Fly.io."
        else
            echo "🚀 Creating new app with a different name..."
            echo "This will create a new app on Fly.io and generate a new fly.toml file."
            echo "When prompted, select 'No' for deploying now, as we need to set up the database first."
            flyctl launch --no-deploy
            
            # Get the app name from the newly generated fly.toml
            app_name=$(grep "app =" fly.toml | cut -d '"' -f2 || grep "app =" fly.toml | cut -d "'" -f2 || echo "charms-explorer-indexer")
            echo "📋 New app name from fly.toml: $app_name"
        fi
    fi
else
    echo "🚀 Step 2: Launching the application with fly launch..."
    echo "This will create a new app on Fly.io and generate a fly.toml file."
    echo "When prompted, select 'No' for deploying now, as we need to set up the database first."
    flyctl launch --no-deploy
    
    # Get the app name from the generated fly.toml
    if [ -f "fly.toml" ]; then
        app_name=$(grep "app =" fly.toml | cut -d '"' -f2 || grep "app =" fly.toml | cut -d "'" -f2 || echo "charms-explorer-indexer")
        echo "📋 App name from fly.toml: $app_name"
    else
        read -p "Enter app name (default: charms-explorer-indexer): " app_name
        app_name=${app_name:-charms-explorer-indexer}
    fi
fi

# Step 3: Set up PostgreSQL database
echo "🔍 Step 3: Setting up PostgreSQL database..."
echo "Note: Fly.io automatically generates secure database credentials."
echo "      These credentials are included in the DATABASE_URL that will be set in the next step."

read -p "Enter database name (default: charms-indexer-db): " db_name
db_name=${db_name:-charms-indexer-db}
read -p "Enter organization (default: charms-inc): " org
org=${org:-charms-inc}

# Check if the database already exists
if flyctl apps list --org "$org" | grep -q "$db_name"; then
    echo "✅ Database $db_name already exists in organization $org."
    echo "   Using existing database."
else
    echo "Creating new PostgreSQL database..."
    read -p "Enter region (default: sjc): " region
    region=${region:-sjc}
    
    # Try to create the database
    if flyctl postgres create --name "$db_name" --region "$region" --org "$org"; then
        echo "✅ PostgreSQL database created: $db_name"
        echo "   Username and password are automatically generated by Fly.io"
    else
        echo "❌ Error: Could not create database."
        echo "   Please check if the database already exists in another organization."
        echo "   Available organizations:"
        flyctl orgs list
        exit 1
    fi
fi

# Step 4: Attach PostgreSQL database
echo "🔗 Step 4: Attaching database to application..."
flyctl postgres attach "$db_name" -a "$app_name" --yes
echo "✅ Database attached."
echo "   The DATABASE_URL environment variable has been automatically set."
echo "   This URL contains the auto-generated username, password, and connection details."

# Step 5: Configure environment variables
echo "🔧 Step 5: Setting environment variables..."

# Create a temporary file with all environment variables
echo "Setting all environment variables at once..."
cat > .env-deploy.tmp << EOF
BITCOIN_RPC_HOST=bitcoind-t4-test.fly.dev
BITCOIN_RPC_PORT=48332
BITCOIN_RPC_USER=hello
BITCOIN_RPC_PASSWORD=world
BITCOIN_NETWORK=testnet4
CHARMS_API_URL=https://api-t4.charms.dev
BLOCKS_UNTIL_FINALIZED=0
PROCESS_BLOCK_INTERVAL_MS=120000
GENESIS_BLOCK_HASH=00000000338e09eb14a8df7f186c04db96c351b414fc186f4f4eea0c5941c1b2
GENESIS_BLOCK_HEIGHT=57604
TX_ORDINAL_BLOCK_HEIGHT_OFFSET=10000
RUST_LOG=info
EOF

# Set all environment variables at once
flyctl secrets import --app "$app_name" < .env-deploy.tmp
rm .env-deploy.tmp
echo "✅ All environment variables set."

# Step 6: Deploy application
echo "🚀 Step 6: Deploying application..."
read -p "Do you want to deploy now? (y/n): " deploy_now
if [[ "$deploy_now" == "y" ]]; then
    flyctl deploy --app "$app_name"
    
    # Step 7: Verify deployment
    echo "✅ Step 7: Deployment verification..."
    flyctl status --app "$app_name"
    echo "ℹ️ Monitor logs with: flyctl logs --app $app_name"
    
    echo "🎉 Deployment of charms-indexer successful!"
else
    echo "Deployment skipped. You can deploy later with: flyctl deploy --app $app_name"
    echo "Or use redeploy.sh for subsequent deployments."
fi
