//! SeaORM Entity. Generated by sea-orm-codegen.

use chrono::NaiveDateTime;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use serde_json::Value;

// Composite PK (txid, vout, app_id) — a single UTXO may carry multiple
// distinct charm tokens (different app_indices in the NormalizedCharms
// map). The PK was (txid, vout) until anomaly A5; that lost multi-token
// outputs on `ON CONFLICT DO NOTHING`. `mark_charms_as_spent_batch`
// still matches on (txid, vout) so spending a UTXO flips every token in
// it.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "charms")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub txid: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub vout: i32,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub app_id: String,
    #[sea_orm(nullable)]
    pub block_height: Option<i32>,
    pub data: Value,
    pub date_created: NaiveDateTime,
    #[sea_orm(column_type = "Text")]
    pub asset_type: String,
    #[sea_orm(column_type = "Text")]
    pub blockchain: String,
    #[sea_orm(column_type = "Text")]
    pub network: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub address: Option<String>,
    pub spent: bool,
    pub amount: i64,
    // TIMESTAMPTZ in DB → must use DateTimeWithTimeZone, NOT NaiveDateTime
    #[sea_orm(nullable)]
    pub mempool_detected_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub tags: Option<String>,
    pub verified: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
