//! SeaORM Entity. Generated by sea-orm-codegen.

use chrono::NaiveDateTime;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use serde_json::Value;

// [RJJ-S01] Updated to use composite primary key (txid, vout)
// Removed charmid field, added app_id field
// [RJJ-MEMPOOL] Added support for mempool tracking with nullable block_height
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "charms")]
pub struct Model {
    #[sea_orm(primary_key, column_type = "Text")]
    pub txid: String,
    #[sea_orm(primary_key)]
    pub vout: i32,
    #[sea_orm(nullable)]
    pub block_height: Option<i32>,
    pub data: Value,
    pub date_created: NaiveDateTime,
    #[sea_orm(column_type = "Text")]
    pub asset_type: String,
    #[sea_orm(column_type = "Text")]
    pub blockchain: String,
    #[sea_orm(column_type = "Text")]
    pub network: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub address: Option<String>,
    pub spent: bool,
    #[sea_orm(column_type = "Text")]
    pub app_id: String,
    pub amount: i64,
    #[sea_orm(nullable)]
    pub mempool_detected_at: Option<NaiveDateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub tags: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
