//! SeaORM Entity. Generated by sea-orm-codegen.

use chrono::NaiveDateTime;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "charms")]
pub struct Model {
    #[sea_orm(primary_key, column_type = "Text")]
    pub txid: String,
    #[sea_orm(column_type = "Text")]
    pub charmid: String,
    pub block_height: i32,
    pub data: Value,
    pub date_created: NaiveDateTime,
    #[sea_orm(column_type = "Text")]
    pub asset_type: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
