//! SeaORM Entity. Generated by sea-orm-codegen.

pub use super::assets::Entity as Assets;
pub use super::bookmark::Entity as Bookmark;
pub use super::charms::Entity as Charms;
pub use super::summary::Entity as Summary;
pub use super::transactions::Entity as Transactions;
