//! SeaORM Entity. Generated by sea-orm-codegen.

use chrono::NaiveDateTime;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "transactions")]
pub struct Model {
    #[sea_orm(primary_key, column_type = "Text")]
    pub txid: String,
    pub block_height: i32,
    pub ordinal: i64,
    pub raw: Value,
    pub charm: Value,
    pub updated_at: NaiveDateTime,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub confirmations: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
